### ISSUE TITLE
TaskLoadImageData.swift line 140 TaskLoadImageData.dataTask(didReceiveData:response:)

### ISSUE THREAD

**Issue by siddew201** [kean/Nuke#589] opened 2022-08-16 07:41 UTC
We are getting crash at end user side. Please help us to resolve this issue. 

Crashed: com.github.kean.Nuke.ImagePipeline
0  libswiftFoundation.dylib       0xfe768 specialized __DataStorage.init(bytes:length:copy:deallocator:offset:) + 344
1  libswiftFoundation.dylib       0xab68 Data.InlineSlice.ensureUniqueReference() + 152
2  libswiftFoundation.dylib       0x12fb0 Data.InlineSlice.append(contentsOf:) + 36
3  libswiftFoundation.dylib       0x13d5c Data._Representation.append(contentsOf:) + 568
4  Nuke                           0x48930 TaskLoadImageData.dataTask(didReceiveData:response:) + 140 (TaskLoadImageData.swift:140)
5  Nuke                           0x49ed4 partial apply for closure #1 in TaskLoadImageData.loadImageData(finish:) + 93 (TaskLoadImageData.swift:93)
6  Nuke                           0x154e8 specialized _DataLoader.urlSession(_:dataTask:didReceive:) + 212 (DataLoader.swift:212)
7  Nuke                           0x149f8 @objc _DataLoader.urlSession(_:dataTask:didReceive:) + 4408134136 (<compiler-generated>:4408134136)
8  FirebasePerformance            0x196bc __InstrumentURLSessionDataTaskDidReceiveData_block_invoke + 119 (FPRNSURLSessionDelegateInstrument.m:119)
9  CFNetwork                      0x609a8 CFHTTPCookieStorageCreateFromFile + 3208
10 Foundation                     0x4e3ec __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
11 Foundation                     0x5faa0 -[NSBlockOperation main] + 100
12 Foundation                     0x39adc __NSOPERATION_IS_INVOKING_MAIN__ + 20
13 Foundation                     0x4a01c -[NSOperation start] + 764
14 Foundation                     0x4d4e8 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
15 Foundation                     0x5acfc __NSOQSchedule_f + 180
16 libdispatch.dylib              0x46048 _dispatch_block_async_invoke2 + 104
17 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
18 libdispatch.dylib              0x3f4a4 _dispatch_lane_serial_drain$VARIANT$armv81 + 600
19 libdispatch.dylib              0x3ff44 _dispatch_lane_invoke$VARIANT$armv81 + 388
20 libdispatch.dylib              0x498e0 _dispatch_workloop_worker_thread + 608
21 libsystem_pthread.dylib        0x1e10 _pthread_wqthread + 284
22 libsystem_pthread.dylib        0x193c start_wqthread + 8

**Comment by kean** [comment] 2022-08-16 22:12
Duplicate of https://github.com/kean/Nuke/issues/572. I'm going to address it in the upcoming patch release by disabling progressive rendering by default for now. Not sure what's the right long-term solution yet.

**Comment by kean** [comment] 2022-08-17 00:03
I disabled incremental delivery in [11.11.1](https://github.com/kean/Nuke/releases/tag/11.1.1). It should mitigate the issue, and I'll look for a better long-term solution later.

**Closed by kean** 2022-08-17 00:03 UTC
Labels: crash

**Comment by siddew201** [comment] 2022-08-17 04:44
thanks @kean

**Comment by DanielLiuCD** [comment] 2023-01-09 03:18
I suspect it's a memory warning. I noticed that every crashed user had 40-50M of available memory. Is the out-of-memory condition tested.   @kean
