### ISSUE TITLE
Cannot override ImageDisplayingView method in UIImageView subclass

### ISSUE THREAD

**Issue by Morji** [kean/Nuke#38] opened 2015-10-31 13:53 UTC
I'm trying to wrap the Nuke functionality in my own UIImageView subclass. Due to      `ImageLoadingViewExtensions.swift`, I am unable to override the the `func nk_imageTask(task: ImageTask, didFinishWithResponse response: ImageResponse, options: ImageViewLoadingOptions?)` where I want to place some custom logic. 

Is there any way this can be changed to allow me to do that?

**Comment by kean** [comment] 2015-10-31 14:22
You can't override those methods in your subclass. But you can override them in an extension of the subclass.

I've mentioned it in a comments:

>  /** Note that classes cannot override declarations from extensions. If you have a subclass of a class that already implements ImageDisplayingView protocol in an extension (like UIImageView) you won't be able to override methods of this protocol in a subclass itself. But you can override them in an extension of the subclass.
    */
    public func nk_imageTask(task: ImageTask, didFinishWithResponse response: ImageResponse, options: ImageViewLoadingOptions?) {
```

**Comment by kean** [comment] 2015-10-31 14:35
Hmm, I was able to override this method in an extension of UIImageView subclass in Swift 2.0. Doesn't seem to work now.

**Comment by kean** [comment] 2015-10-31 14:40
As a workaround you can set a custom handler on ImageViewLoadingController:

```swift
class CustomImageView: UIImageView {
    override init(frame: CGRect) {
        self.nk_imageLoadingController.handler = { task, response, options in
            // your nk_imageTask(task: ImageTask, didFinishWithResponse response: ImageResponse, options: ImageViewLoadingOptions?) implementation
        }
        super.init(frame: frame)
    }
}
```

**Comment by Morji** [comment] 2015-10-31 14:48
Thank, Kean, that works great. Want me to close the issue or will you leave it open to investigate?

**Comment by kean** [comment] 2015-10-31 15:07
Please leave it open. Users should be able to override methods declared in ImageDisplayingView protocol, that was the intended behaviour. I should figure out why dynamic dispatch doesn't work here.

**Comment by kean** [comment] 2015-11-12 23:32
After some research I've found several different issues related to methods dispatch with protocol extensions that still hasn't been fixed in Xcode 7.

Here's the related one http://www.openradar.me/23067007. You have class `A` that conforms to protocol `P` that has default implementation of method `foo` defined in a protocol. If you create subclass `B` of class `A` and implement method `foo` it never gets called unless class `A` also provide an implementation of `foo` method

And that's how it works in Nuke:

1) If you implement `nk_imageTask(_:didFinishWithResponse:options:)` method in a class that declares conformance to `ImageDisplayingView` protocol (for instance `UIImageView`) then this method gets called (as expected):

```swift
    extension UIImageView: ImageDisplayingView, ImageLoadingView {
        public var nk_image: UIImage? {
            get { return self.image }
            set { self.image = newValue }
        }
        
        public func nk_imageTask(task: ImageTask, didFinishWithResponse response: ImageResponse, options: ImageViewLoadingOptions?) {
            print("UIImageView method called")
        }
    }
```

2) However if you implement `nk_imageTask(_:didFinishWithResponse:options:)` method in a subclass of `UIImageView` and don't implement this method in `UIImageView` then this method never gets called (this is a bug which is the same as in the radar).

```swift
public class NKImageView: UIImageView {
    
}

extension NKImageView {
    public override var nk_image: UIImage? {
        get { return self.image }
        set { self.image = newValue }
    }
    
    public func nk_imageTask(task: ImageTask, didFinishWithResponse response: ImageResponse, options: ImageViewLoadingOptions?) {
        print("NKImageView method never gets called")
    }
}
```

3) If you implement `nk_imageTask(_:didFinishWithResponse:options:)` method in both `UIImageView` and `NKImageView` classes then you get the following error in `NKImageView` class (as of Xcode 7.1):

<img width="766" alt="screen shot 2015-11-13 at 02 29 55" src="https://cloud.githubusercontent.com/assets/1567433/11134512/740f0210-89ae-11e5-8f49-9e4ed11d3925.png">

This is pretty obvious. And as you can see properties already can be overridden and get called as expected.

**Comment by kean** [comment] 2015-11-12 23:40
This behaviour doesn't match the documentation that clearly states that:

> You can use protocol extensions to provide a default implementation to any method or property requirement of that protocol. If a conforming type provides its own implementation of a required method or property, that implementation will be used instead of the one provided by the extension.

Same thing holds with extensions with `where` clauses (which I also tested):

> If a conforming type satisfies the requirements for multiple constrained extensions that provide implementations for the same method or property, Swift will use the implementation corresponding to the most specialized constraints.

**Closed** 2016-02-26 17:20 UTC
Labels: question
