### ISSUE TITLE
Images disappear when scrolling a list back and forth (SwiftUI) 

### ISSUE THREAD

**Issue by mickey4u** [kean/Nuke#720] opened 2023-08-29 12:43 UTC
I am new to SwiftUI and NukeUI. I am trying to use NukeUI to cache images using the code below. Now the problem I am facing is when I scroll though the list of items and back the images disappear and only reappear when I click anywhere on the screen. Am I doing something wrong?

```    
let imageUrl = security.tokenImageUrl!
      LazyImage(source: URL(string: imageUrl)){ state in
          if let image = state.image {
              image.aspectRatio(contentMode: .fill)
                  .clipShape(Circle())
                  .cornerRadius(5)
                  .padding(8)
          } else if state.error != nil {
              Circle().cornerRadius(5)
                  .foregroundColor(.red)
          } else {
              Circle().cornerRadius(5)
                  .foregroundColor(.green)
          }
      }
      .onCreated{ image in
      }
```

**Comment by kean** [comment] 2024-02-18 17:56
I'm going to close it because I believe it's been addressed in the reworked implementation. Please, re-open if you are still able to reproduce it with the latest version.

**Closed by kean** 2024-02-18 17:56 UTC
Labels: question
