### ISSUE TITLE
Images not being displayed

### ISSUE THREAD

**Issue by luis-valdes-21b** [kean/Nuke#396] opened 2020-10-14 13:24 UTC
Hi,

We are using Nuke in our app, and since a few weeks ago, all the images are not displayed for many of our users. Usually, this happens first thing in the morning when they open the app, but if they close it and reopen it again, the images are displayed just fine! Note this happens with local images too (loaded from the photo library), and only on iOS (Android works fine!). I've been trying to reproduce the issue with no success, but we are getting many reports from our users in the field complaining about this.

Do you have any idea about what might be problem? Or have you ever experienced something similar?

Thank you!

**Comment by kean** [comment] 2020-10-14 16:03
Hey, @luis-valdes-21b.

- What version are you using?
- Are you using the default pipeline configuration? If not, what is the configuration?
- Could you mind sharing a sample of how you use it?
- Are you able to reproduce it / capture any of the error messages?

**Comment by luis-valdes-21b** [comment] 2020-10-15 11:23
Hi @kean,

Thank you for your support!

Here are the details:
1. Nuke 9.1.2
2. Not anymore. In order to try to fix the issue, we started using the following configuration (via https://github.com/kean/Nuke/issues/389#issuecomment-692943699), but the problem is still there.
```swift
extension ImagePipeline {
    static var nonResumablePipeline: ImagePipeline {
        var configuration = ImagePipeline.Configuration()
        configuration.isResumableDataEnabled = false
        let pipeline = ImagePipeline(configuration: configuration)
        return pipeline
    }
}
```
3. Sure, this is how we use Nuke in an `UIImageView` extension:
```swift
let transition: ImageLoadingOptions.Transition? = durationTransition == 0 ? nil : .fadeIn(duration: durationTransition ?? 0.1)
var options = ImageLoadingOptions(placeholder: placeholderImage, transition: transition)
options.pipeline = .nonResumablePipeline
let completion: ImageTask.Completion = { result in
    guard let image = try? result.get().image else {
        errorClosure?(TWError.custom(urlString.orEmpty))
        return
    }
    successClosure?(image)
}
Nuke.loadImage(with: url, options: options, into: self, completion: completion)
```
4. We are not able to reproduce the error in my devices, so I've made a new build with more logs in order to investigate what's going on.

**Comment by kean** [comment] 2020-10-15 16:55
The issue outlined in https://github.com/kean/Nuke/issues/389#issuecomment-692943699 seems to be specific to the server. I haven't received or saw issues with resumable data.

Looks like you have a standard configuration. It is suppose to work with no issues. Please let me know once you get the logs, I can't recommend anything based on just this info.

**Comment by luis-valdes-21b** [comment] 2020-10-27 15:29
Hi @kean,

We still don't know why this is happening, but do we have to keep a reference to the `ImageTask` returned when calling `Nuke.loadImage(with:options:into:progress:completion:`? We are not keeping a reference to it, so maybe it is dealloc'ed and the download is cancelled?

**Comment by kean** [comment] 2020-10-27 15:44
You don't need to keep a reference to `ImageTask`, it is merged with `@disposableResult` for this reason.  

> so maybe under certain conditions it is dealloc'ed and the download is cancelled
I don't rule this out, but this is unlikely. Also, keep in mind that the completion closure doesn't get called if the request gets cancelled. The request gets cancelled automatically if you request a new image into the same target view or the view is deallocated.

**Comment by kean** [comment] 2020-11-22 02:53
Hey @luis-valdes-21b, do you have any updates on this issue?

**Comment by luis-valdes-21b** [comment] 2020-11-23 16:07
Hi @kean. The issue is no longer happening, so my guess is there was a problem with the CDN, or maybe iOS 14.0, but we are not sure. It'd suggest to close this issue in GitHub, since we are not investing in finding the root cause for the moment. Thank you very much for your support! 🙏

**Closed** 2020-11-23 16:14 UTC
