### ISSUE TITLE
Various Memory Leaks (v7.5.2)

### ISSUE THREAD

**Issue by jz709u** [kean/Nuke#288] opened 2019-08-06 03:50 UTC
Nuke version 7.5

Cancelation Token Source, Operation, Task, Container

<img width="706" alt="Screen Shot 2019-08-06 at 12 46 51" src="https://user-images.githubusercontent.com/19835598/62509967-4b2e6a80-b848-11e9-89c1-e20b46ada675.png">

seems like there is a giant retain cycle 57 nodes 

<img width="568" alt="Screen Shot 2019-08-06 at 12 45 25" src="https://user-images.githubusercontent.com/19835598/62509928-2639f780-b848-11e9-9609-bbe4a1c2d8c3.png">

am I using anything wrong.

**Comment by kean** [comment] 2019-08-06 07:52
Could you please update to Nuke 7.6.3 or Nuke 8 and see if the issue still persists?

P.S. CancellationTokenSource is tricky to use correctly and often leads to retain cycles, that's why I remove this pattern in Nuke 8. The memory management is much clearer in the new versions.

**Comment by jz709u** [comment] 2019-08-09 08:34
Since I need to support iOS 9.0.  I am unable to upgrade past 7.5.2.  any suggestions on ImageTasks and how to use them or not use them?

**Comment by kean** [comment] 2019-08-14 07:50
The tasks (`ImageTask`) are always used under the hood. Please, first, make sure you are not creating a retain cycle in your own code. If the issue is in the framework, I'm sorry, I don't think I'm going to be able to help with tracking the defects in the outdated versions. It would be best if you could drop iOS 9.0 dependency, upgrade and see if it still reproduces . As another option, If you could fix the issue in 7.5.2, I would also be happy to release a patch to 7.5.

**Comment by kean** [comment] 2019-09-26 06:45
I'm going to close this one since I'm not supporting pre 8.0 versions. I hope you don't mind.

**Closed by kean** 2019-09-26 06:45 UTC
Labels: bug

**Comment by kean** [comment] 2019-09-28 20:23
I run generational analysis using Nuke 7.6.3, no leaks there.
