### ISSUE TITLE
macOS 10.13.4 - HTTP Load failed

### ISSUE THREAD

**Issue by CWalig** [kean/Nuke#157] opened 2018-04-18 07:10 UTC
Hi,

First of all, thanks for Nuke, it saved me an incredible amount of time and it worked flawlessly.

Since I upgraded to High Sierra (10.13.4) the following error are being logged in the Xcode Console.
Everything works as expected, however the console is flooded with the following lines.

```
2018-04-18 19:00:11.675594+1200 xx[31595:3383774] Task <66C9A459-E677-418A-BD3A-6E9D15DA0130>.<124> HTTP load failed (error code: 100 [1:100])
2018-04-18 19:00:11.675671+1200 xx[31595:3383772] Task <66C9A459-E677-418A-BD3A-6E9D15DA0130>.<124> finished with error - code: 100
2018-04-18 19:00:11.704761+1200 xx[31595:3383983] Task <E20CE7FE-DE34-42DD-96B9-4ED496BC4514>.<78> finished with error - code: -999
```

I did some research It appears to be some malformed request. I am requesting a simple png image.
Unfortunately I am unable to provide the specific URLs, but it can be easily reproduced with the following one `https://retreatnetwork.s3.amazonaws.com/wp-content/uploads/2016/04/2016-04-18_ScreenShot20160418at70328pm1460979420-1024x686.png`.

Let me know if you have any idea,
Thanks!

**Comment by kean** [comment] 2018-04-18 07:59
Hey, @CWalig! Thanks for the report. I haven't updated to 10.13.4 yet, I'm planning to during this weekend. Which version of Nuke, Xcode, Swift, Platform are you using?

**Comment by CWalig** [comment] 2018-04-18 10:13
Good point I should have mentioned that.

Xcode: 9.3 (9E145)
Nuke: 5.2
Swift: 4.1
Platform: macOS

I took some time to make a dummy project.  https://cl.ly/382s2r0i2B11 

In my own project I am using Nuke inside a `NSTableView`'s cell. To reproduce the issue with a single image, I made a simple loop. Additionally to make sure Nuke is doing a new network request every time, I am clearing the cache.

Let me know what you think, I might have missed something 😄👍

**Comment by kean** [comment] 2018-04-22 10:49
Hey @CWalig!

```
2018-04-18 19:00:11.704761+1200 xx[31595:3383983] Task <E20CE7FE-DE34-42DD-96B9-4ED496BC4514>.<78> finished with error - code: -999
```

This error is trivial, it's just a cancellation of a task. When you call `loadImage(with:into:)` in a loop (not a valid use case) in 5.2 some of the requests (not all) manage to be resumed and then cancelled.

```
2018-04-18 19:00:11.675594+1200 xx[31595:3383774] Task <66C9A459-E677-418A-BD3A-6E9D15DA0130>.<124> HTTP load failed (error code: 100 [1:100])
2018-04-18 19:00:11.675671+1200 xx[31595:3383772] Task <66C9A459-E677-418A-BD3A-6E9D15DA0130>.<124> finished with error - code: 100
```

This one though is interesting. The code [100 is a "Protocol Error"](https://stackoverflow.com/questions/41461481/error-domain-nsposixerrordomain-code-100-protocol-error). I was not able to reproduce this particular error on my machine (still running 10.3.3) but I sometimes receive the following error messages instead:

```
2018-04-22 12:39:44.345907+0200 NukeErrorMessage[8494:378626] [BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
```

It might be something to do with outdated / misconfigured SSL. I'm not sure I'm going to be able to help debugging this. I'm almost certain that's not something that Nuke does that triggers it because it uses high-level APIs in the simplest way possible. I'm going to close this, if you find a solution please post it here.

**Closed by kean** 2018-04-22 10:49 UTC

**Comment by kean** [comment] 2018-04-23 05:12
I see, I was also surprised that on macOS URLSession seems to send those logs automatically. Those logs aren't coming from the project, they are coming from URLSession itself.
