### ISSUE TITLE
Strange image rendering

### ISSUE THREAD

**Issue by fabianfabian** [kean/Nuke#730] opened 2023-10-12 03:23 UTC
Has anyone seen this strange image rendering before, could it be related to Nuke?
This is the correct image, and how it is supposed to look:
![](https://i.nostr.build/y8ZG.jpg)

Here is that image downloaded and rendered in 2 different applications, the right side using Nuke:
![](https://i.nostrimg.com/906d98e8638926c455ea9ee71789366e20522ae219c22633eb27bdf6600bb7b7/file.jpeg)

I'm not sure if it is related to Nuke or something else in the application so I'm wondering if anyone has seen something like this before. It doesn't happen on all images, very rare I think.

**Comment by kean** [comment] 2023-10-17 02:03
I can't think of a single reason why that might happen, but I'm inclined to close it because it's highly unlikely it has to do with the framework. The framework doesn't handle rendering.

Do you have the code for the second app? Is there a way to reproduce it?

**Closed** 2023-11-05 22:07 UTC
