### ISSUE TITLE
Fresh images with `must-revalidate` aren't rendered if prefetched

### ISSUE THREAD

**Issue by leandrofavarin** [kean/Nuke#728] opened 2023-10-10 10:55 UTC
## Summary

Nuke does not render _fresh_ (resource cached and attempted to be reused while max-age hasn't turned it into _stale_) images that were prefetched to disk if they were fetched with the `must-revalidate` element inside `Cache-Control` header. 

## Our use-case

We prefetch important images that are displayed throughout our app on app start, like so:
```swift
let prefetcher = ImagePrefetcher(destination: .diskCache)
prefetcher.startPrefetching(with: <list of urls>)
```

And displayed in our UI:
```swift
LazyImage(url: <an image url>)
```

## How to reproduce

- I ran [NukeDemo](https://github.com/kean/NukeDemo) with Charles enabled, rewriting the `Cache-Control` header appending `must-revalidate` to all githubusercontent image urls (the sample urls).
- Then I added the above prefetcher to `applicationDidFinishLaunching(:)`. After disabling internet connectivity and clicking on `Prefetch (SwiftUI)` (on the `MenuViewController`), the images were all missing. It would have been all displayed if the rewrite hadn't taken place. 

<img width="1101" alt="Screenshot 2023-10-10 at 12 31 10" src="https://github.com/kean/Nuke/assets/3139181/d8cf32ec-3394-4427-a607-322fa35e8c6a">

<img width="1092" alt="Screenshot 2023-10-09 at 17 12 41" src="https://github.com/kean/Nuke/assets/3139181/09293784-21eb-4d79-9856-41539eff18a7">

**Comment by kean** [comment] 2023-10-17 02:00
Hey, @leandrofavarin. I may be missing something, but it looks like it works as expected. The `must-invalidate` header dictates that the client validates the resource (using ETag or Last-Modified) with a server every time it tries to serve it to the client.  Please, see the [Serving Stale Images](https://kean-docs.github.io/nuke/documentation/nuke/cache-layers#Serving-Stale-Images) section for more info and some suggested solutions.

**Comment by leandrofavarin** [comment] 2023-10-17 08:06
Hi kean, thanks for taking the time to answer.

I may have misunderstood how `must-revalidate` works. 

From [MSDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), I found:
>The must-revalidate response directive indicates that the response can be stored in caches and can be reused while [fresh](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#fresh_and_stale_based_on_age). If the response becomes [stale](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#fresh_and_stale_based_on_age), it must be validated with the origin server before reuse.

And from [w3.org](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.4):
>must-revalidate
Because a cache MAY be configured to ignore a server's specified expiration time, and because a client request MAY include a max- stale directive (which has a similar effect), the protocol also includes a mechanism for **the origin server to require revalidation of a cache entry on any subsequent use**. When the must-revalidate directive is present in a response received by a cache, **that cache MUST NOT use the entry after it becomes stale to respond to a subsequent request without first revalidating it with the origin server**. (I.e., the cache MUST do an end-to-end revalidation every time, if, based solely on the origin server's Expires or max-age value, the cached response is stale.)
The must-revalidate directive is necessary to support reliable operation for certain protocol features. In all circumstances an HTTP/1.1 cache MUST obey the must-revalidate directive; in particular, if the cache cannot reach the origin server for any reason, it MUST generate a 504 (Gateway Timeout) response.
Servers SHOULD send the must-revalidate directive if and only if failure to revalidate a request on the entity could result in incorrect operation, such as a silently unexecuted financial transaction. Recipients MUST NOT take any automated action that violates this directive, and MUST NOT automatically provide an unvalidated copy of the entity if revalidation fails.
Although this is not recommended, user agents operating under severe connectivity constraints MAY violate this directive but, if so, MUST explicitly warn the user that an unvalidated response has been provided. The warning MUST be provided on each unvalidated access, and SHOULD require explicit user confirmation.

(emphasis mine).

From the w3.org, the first part in bold agrees with you. But I am hanging on this 2nd bold part, which in my interpretation allows clients to use a cache entry if they're not stale without communicating to the server. I believe in this because if the server wanted to _always_ have revalidation, regardless of the entry's age, then `no-cache` must have been used? From [w3.org](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.1):

>no-cache
If the no-cache directive does not specify a field-name, then a cache MUST NOT use the response to satisfy a subsequent request without successful revalidation with the origin server. This allows an origin server to prevent caching even by caches that have been configured to return stale responses to client requests.
If the no-cache directive does specify one or more field-names, then a cache MAY use the response to satisfy a subsequent request, subject to any other restrictions on caching. However, the specified field-name(s) MUST NOT be sent in the response to a subsequent request without successful revalidation with the origin server. This allows an origin server to prevent the re-use of certain header fields in a response, while still allowing caching of the rest of the response.

It's well known that interpreting these protocol rules are hard, specially for a non-native English speaker like myself.

**Comment by kean** [comment] 2023-10-17 14:25
No, I think you are right. I checked [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control), and your interpretation seems to be correct. I also haven't worked with HTTP cache in a while, so take this with a grain of salt.

On iOS (and when using `URLSession`), the default behavior matches exactly what MDN describes as a `must-revalidate`. I also found the following [answer on SO](https://stackoverflow.com/questions/51778155/nsurlcache-together-with-nsurlsession-does-not-respect-cache-control-max-age#:~:text=The%20%22must%2Drevalidate%22%20response,validation%20on%20the%20origin%20server.). Assuming it's accurate, it's understandable why Apple would also opt-in to ignore `max-age` when `must-revalidate` is present.

**Comment by kean** [comment] 2023-10-19 13:15
You can switch to a [disk cache](https://kean-docs.github.io/nuke/documentation/nuke/getting-started#Caching) that ignores `cache-control` headers by changing the pipeline configuration:

```swift
ImagePipeline.shared = ImagePipeline(configuration: .withDataCache)
```

**Comment by leandrofavarin** [comment] 2023-10-19 15:44
This would allow the views to read from the declared cache directly, right?

And would something else have to be modified at the callsite of the View? I have tried to reproduce declaring the line above before I begin prefetching, and the problem (images aren't rendered) persists.

**Comment by kean** [comment] 2024-04-24 02:01
I'm going to close it because it's been a while. I'm still unsure if there is an issue on the framework side and if there is how to reproduce it. If the issue persists, please, feel free to reopen it, but I would appreciate if you could provide the reproduction steps.

**Closed by kean** 2024-04-24 02:01 UTC
Labels: question
