### ISSUE TITLE
App Store Connect Operation Warning - removeAll

### ISSUE THREAD

**Issue by jordanwhitney** [kean/Nuke#605] opened 2022-09-23 12:27 UTC
When uploading an archive to App Store Connect, Xcode Version 14.0 (14A309), the following warning appears:

App Store Connect Operation Warning
The app references non-public selectors in Payload/<My App>.app/Frameworks/Nuke.framework/Nuke: removeAll

This looks similar to #531

**Comment by kean** [comment] 2022-09-23 15:25
It's part of the public API. I can't remove it. I hope Apple fixes App Store Connect validation. I'm going to submit a radar.

**Comment by jordanwhitney** [comment] 2022-09-23 16:38
It did seem like common public API. Thanks for filing a radar.

**Comment by kean** [comment] 2022-09-25 14:07
Closing as duplicate of https://github.com/kean/Nuke/issues/604#issuecomment-1256577301

**Closed by kean** 2022-09-25 14:07 UTC
