### ISSUE TITLE
iOS 18 Crash in `TaskFetchWithPublisher.loadData` line 49

### ISSUE THREAD

**Issue by choulepoka** [kean/Nuke#821] opened 2024-11-02 20:11 UTC
I have been monitoring this new crash ever since iOS 18 was released. The crash seems to occurs exclusively on iOS 18 even though still more than 80% of our users are running on iOS 17. I have been trying to reproduce with no success.

Here is the full crash log as reported by Sentry.

```
OS Version: iOS 18.1 (22B83)
Report Version: 104

Exception Type: EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0 at 0x00000001956d7ca0
Crashed Thread: 25

Application Specific Information:
Exception 6, Code 1, Subcode 6801947808

Thread 25 Crashed:
0   Foundation                      0x3170dcca0         __DataStorage.init
1   Foundation                      0x3171eb710         Data.InlineSlice.init
2   Foundation                      0x3170db67c         Data._Representation.append
3   Foundation                      0x3177a9afc         __DataStorage.withUnsafeBytes<T>
4   Foundation                      0x3171aa6b4         Data.append
5   App                             0x2060330d4         closure in TaskFetchWithPublisher.loadData (TaskFetchWithPublisher.swift:49)
6   App                             0x2051cb534         thunk for closure
7   libdispatch.dylib               0x3292b636c         _dispatch_call_block_and_release
8   libdispatch.dylib               0x3292b80cc         _dispatch_client_callout
9   libdispatch.dylib               0x3292bf6d4         _dispatch_lane_serial_drain
10  libdispatch.dylib               0x3292c01dc         _dispatch_lane_invoke
11  libdispatch.dylib               0x3292cb254         _dispatch_root_queue_drain_deferred_wlh
12  libdispatch.dylib               0x3292caaa0         _dispatch_workloop_worker_thread
13  libsystem_pthread.dylib         0x42a102c78         _pthread_wqthread

Thread 0
0   ImageIO                         0x324bfa530         IIOImageProviderInfo::CopyIOSurface
1   QuartzCore                      0x31cddb680         CA::Render::copy_image
2   QuartzCore                      0x31cde7adc         CA::Render::prepare_image
3   QuartzCore                      0x31cde7930         CA::Layer::prepare_contents
4   QuartzCore                      0x31cde7130         CA::Layer::prepare_commit
5   QuartzCore                      0x31ce3d91c         CA::Context::commit_transaction
6   QuartzCore                      0x31cdbc7c0         CA::Transaction::commit
7   QuartzCore                      0x31cdffa08         CA::Transaction::flush_as_runloop_observer
8   UIKitCore                       0x31e87b564         _UIApplicationFlushCATransaction
9   UIKitCore                       0x31e878b60         __setupUpdateSequence_block_invoke_2
10  UIKitCore                       0x31e8789d4         _UIUpdateSequenceRun
11  UIKitCore                       0x31e878624         schedulerStepScheduledMainSection
12  UIKitCore                       0x31e879598         runloopSourceCallback
13  CoreFoundation                  0x319862324         __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
14  CoreFoundation                  0x3198622b8         __CFRunLoopDoSource0
15  CoreFoundation                  0x31985fe20         __CFRunLoopDoSources0
16  CoreFoundation                  0x31985efb8         __CFRunLoopRun
17  CoreFoundation                  0x31985e82c         CFRunLoopRunSpecific
18  GraphicsServices                0x3b186f1c0         GSEventRunModal
19  UIKitCore                       0x31ebaaeac         -[UIApplication _run]
20  UIKitCore                       0x31ec595b0         UIApplicationMain
21  App                             0x2066125d4         main (main.m:16)
22  <unknown>                       0x1bc48aec8         <redacted>

Thread 1 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x3ba033688         mach_msg2_trap
1   libsystem_kernel.dylib          0x3ba036d94         mach_msg2_internal
2   libsystem_kernel.dylib          0x3ba036cac         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3ba036af8         mach_msg
4   CoreFoundation                  0x31985fa80         __CFRunLoopServiceMachPort
5   CoreFoundation                  0x31985f12c         __CFRunLoopRun
6   CoreFoundation                  0x31985e82c         CFRunLoopRunSpecific
7   Foundation                      0x3171494fc         -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
8   Foundation                      0x31714934c         -[NSRunLoop(NSRunLoop) runUntilDate:]
9   UIKitCore                       0x31ebbe354         -[UIEventFetcher threadMain]
10  Foundation                      0x31715a6c4         __NSThread__start__
11  libsystem_pthread.dylib         0x42a104378         _pthread_start

Thread 2
0   libsystem_kernel.dylib          0x3ba0391b0         __semwait_signal
1   libsystem_c.dylib               0x329357a74         nanosleep
2   libsystem_c.dylib               0x3293b554c         sleep
3   App                             0x2065990e0         monitorCachedData
4   libsystem_pthread.dylib         0x42a104378         _pthread_start

Thread 3 name: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0x3ba033688         mach_msg2_trap
1   libsystem_kernel.dylib          0x3ba036d94         mach_msg2_internal
2   libsystem_kernel.dylib          0x3ba036cac         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3ba036af8         mach_msg
4   App                             0x20657f168         handleExceptions
5   libsystem_pthread.dylib         0x42a104378         _pthread_start

Thread 5 name: com.apple.CFSocket.private
0   libsystem_kernel.dylib          0x3ba03b234         __select
1   CoreFoundation                  0x3198c7958         __CFSocketManager
2   libsystem_pthread.dylib         0x42a104378         _pthread_start

Thread 6 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x3ba033688         mach_msg2_trap
1   libsystem_kernel.dylib          0x3ba036d94         mach_msg2_internal
2   libsystem_kernel.dylib          0x3ba036cac         mach_msg_overwrite
3   libsystem_kernel.dylib          0x3ba036af8         mach_msg
4   CoreFoundation                  0x31985fa80         __CFRunLoopServiceMachPort
5   CoreFoundation                  0x31985f12c         __CFRunLoopRun
6   CoreFoundation                  0x31985e82c         CFRunLoopRunSpecific
7   CFNetwork                       0x31c2abedc         +[__CFN_CoreSchedulingSetRunnable _run:]
8   Foundation                      0x31715a6c4         __NSThread__start__
9   libsystem_pthread.dylib         0x42a104378         _pthread_start

Thread 7
0   libsystem_kernel.dylib          0x3ba033604         semaphore_wait_trap
1   libdispatch.dylib               0x3292b8668         _dispatch_sema4_wait
2   libdispatch.dylib               0x3292b8d1c         _dispatch_semaphore_wait_slow
3   UIKitCore                       0x31ef87da8         block_destroy_helper.122
4   UIKitCore                       0x31ea94114         __30-[UICollectionView reloadData]_block_invoke
5   Foundation                      0x31715a6c4         __NSThread__start__
6   libsystem_pthread.dylib         0x42a104378         _pthread_start

Thread 8
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 9
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 10
0   libsystem_kernel.dylib          0x3ba0395f4         guarded_pwrite_np
1   libsqlite3.dylib                0x3744bd6f0         sqlite3_sourceid
2   libsqlite3.dylib                0x374477e64         sqlite3_free_table
3   libsqlite3.dylib                0x3744812d4         sqlite3_randomness
4   libsqlite3.dylib                0x374477bec         sqlite3_free_table
5   libsqlite3.dylib                0x374468514         sqlite3_value_text
6   libsqlite3.dylib                0x3744680dc         sqlite3_value_text
7   libsqlite3.dylib                0x374441808         sqlite3_finalize
8   libsqlite3.dylib                0x374462544         sqlite3_step
9   libsqlite3.dylib                0x374457744         sqlite3_step
10  App                             0x20575d258         __43-[AMPDatabaseHelper addEventToTable:event:]_block_invoke (AMPDatabaseHelper.m:372)
11  App                             0x20575c540         __51-[AMPDatabaseHelper inDatabaseWithStatement:block:]_block_invoke (AMPDatabaseHelper.m:215)
12  libdispatch.dylib               0x3292b80cc         _dispatch_client_callout
13  libdispatch.dylib               0x3292c774c         _dispatch_lane_barrier_sync_invoke_and_complete
14  App                             0x20575c438         -[AMPDatabaseHelper inDatabaseWithStatement:block:] (AMPDatabaseHelper.m:199)
15  App                             0x20575d178         -[AMPDatabaseHelper addEventToTable:event:] (AMPDatabaseHelper.m:365)
16  App                             0x205766f64         __157-[Amplitude logEvent:withEventProperties:withApiProperties:withUserProperties:withGroups:withGroupProperties:withTimestamp:outOfSession:withMiddlewareExtra:]_block_invoke (Amplitude.m:758)
17  Foundation                      0x3170aecd8         __NSINDEXSET_IS_CALLING_OUT_TO_A_BOOL_BLOCK__
18  Foundation                      0x3170aeb98         -[NSBlockOperation main]
19  Foundation                      0x3170ae994         __NSOPERATION_IS_INVOKING_MAIN__
20  Foundation                      0x3170acbe4         -[NSOperation start]
21  Foundation                      0x31712480c         __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
22  Foundation                      0x31712443c         __NSOQSchedule_f
23  libdispatch.dylib               0x3292c72e4         _dispatch_block_async_invoke2
24  libdispatch.dylib               0x3292b80cc         _dispatch_client_callout
25  libdispatch.dylib               0x3292bb57c         _dispatch_continuation_pop
26  libdispatch.dylib               0x3292babac         _dispatch_async_redirect_invoke
27  libdispatch.dylib               0x3292c9d88         _dispatch_root_queue_drain
28  libdispatch.dylib               0x3292ca58c         _dispatch_worker_thread2
29  libsystem_pthread.dylib         0x42a102c3c         _pthread_wqthread

Thread 11
0   libsystem_pthread.dylib         0x42a0ff480         start_wqthread

Thread 12
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 13
0   libsystem_kernel.dylib          0x3ba038098         __rename
1   libsystem_kernel.dylib          0x3ba038070         rename
2   CFNetwork                       0x31c222060         _CFURLCacheFSWriteCachedResponseToFS
3   CFNetwork                       0x31c212354         __CFURLCache::CreateAndStoreCacheNode
4   libdispatch.dylib               0x3292c72e4         _dispatch_block_async_invoke2
5   libdispatch.dylib               0x3292b80cc         _dispatch_client_callout
6   libdispatch.dylib               0x3292bf6d4         _dispatch_lane_serial_drain
7   libdispatch.dylib               0x3292c0210         _dispatch_lane_invoke
8   libdispatch.dylib               0x3292cb254         _dispatch_root_queue_drain_deferred_wlh
9   libdispatch.dylib               0x3292caaa0         _dispatch_workloop_worker_thread
10  libsystem_pthread.dylib         0x42a102c78         _pthread_wqthread

Thread 14
0   libsystem_pthread.dylib         0x42a0ff480         start_wqthread

Thread 15
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 16
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 17
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 18
0   libsystem_kernel.dylib          0x3ba039ad0         __ulock_wait
1   libdispatch.dylib               0x3292b8abc         _dlock_wait
2   libdispatch.dylib               0x3292b8870         _dispatch_thread_event_wait_slow
3   libdispatch.dylib               0x3292c7a38         __DISPATCH_WAIT_FOR_QUEUE__
4   libdispatch.dylib               0x3292c75e4         _dispatch_sync_f_slow
5   libsystem_trace.dylib           0x34efaf00c         ___os_state_request_for_self_block_invoke
6   libdispatch.dylib               0x3292b636c         _dispatch_call_block_and_release
7   libdispatch.dylib               0x3292b80cc         _dispatch_client_callout
8   libdispatch.dylib               0x3292bf6d4         _dispatch_lane_serial_drain
9   libdispatch.dylib               0x3292c0210         _dispatch_lane_invoke
10  libdispatch.dylib               0x3292cb254         _dispatch_root_queue_drain_deferred_wlh
11  libdispatch.dylib               0x3292caaa0         _dispatch_workloop_worker_thread
12  libsystem_pthread.dylib         0x42a102c78         _pthread_wqthread

Thread 19
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 20
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 21
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 22
0   libsystem_pthread.dylib         0x42a0ff480         start_wqthread

Thread 23
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 24
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 25 Crashed:
0   Foundation                      0x3170dcca0         __DataStorage.init
1   Foundation                      0x3171eb710         Data.InlineSlice.init
2   Foundation                      0x3170db67c         Data._Representation.append
3   Foundation                      0x3177a9afc         __DataStorage.withUnsafeBytes<T>
4   Foundation                      0x3171aa6b4         Data.append
5   APP                            0x2060330d4         closure in TaskFetchWithPublisher.loadData (TaskFetchWithPublisher.swift:49)
6   App                             0x2051cb534         thunk for closure
7   libdispatch.dylib               0x3292b636c         _dispatch_call_block_and_release
8   libdispatch.dylib               0x3292b80cc         _dispatch_client_callout
9   libdispatch.dylib               0x3292bf6d4         _dispatch_lane_serial_drain
10  libdispatch.dylib               0x3292c01dc         _dispatch_lane_invoke
11  libdispatch.dylib               0x3292cb254         _dispatch_root_queue_drain_deferred_wlh
12  libdispatch.dylib               0x3292caaa0         _dispatch_workloop_worker_thread
13  libsystem_pthread.dylib         0x42a102c78         _pthread_wqthread

Thread 26
0   libsystem_kernel.dylib          0x3ba033410         __workq_kernreturn
1   libsystem_pthread.dylib         0x42a102cc4         _pthread_wqthread

Thread 25 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000016fec2528   x2: 0x000000000025c000   x3: 0x00000000003fffff
    x4: 0x0000000003000001   x5: 0x0000000000000003   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x000000016fec30ac   x9: 0x000000000000000c  x10: 0xffffffffffffc000  x11: 0x0000000000000000
   x12: 0x0000000000000001  x13: 0x0000000000000000  x14: 0x00000000001ff800  x15: 0x00000000000007fb
   x16: 0xfffffffffffffff1  x17: 0x00000001fa84e158  x18: 0x0000000000000000  x19: 0x000000000025a3d6
   x20: 0x0000000302687520  x21: 0x0000000357c00000  x22: 0x0000000302687530  x23: 0x000000000025a3d6
   x24: 0x00000003125d3160  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x000000030db9dd00
   x28: 0x000000030a7e0680   fp: 0x000000016fec26f0   lr: 0x00000001956d7c4c   sp: 0x000000016fec26c0
    pc: 0x00000001956d7ca0 cpsr: 0x0000000060000000



EOF
```

**Comment by kean** [comment] 2024-11-15 13:31
It appears to be a duplicate of https://github.com/kean/Nuke/issues/738

**Closed by kean** 2024-11-15 13:31 UTC
