### ISSUE TITLE
ImageProcessor.Resize appears to be inverting the colour of some images

### ISSUE THREAD

**Issue by james-ff** [kean/Nuke#400] opened 2020-11-11 17:24 UTC
## When using the following Image processor setup:
```
let request = ImageRequest(url: url, processors: [ImageProcessors.Resize(size: self.imageView.bounds.size)])
```

### While most of the time images look correct:

![Image from iOS](https://user-images.githubusercontent.com/1874352/98843024-4a6c8700-2442-11eb-9940-bd37d14db0be.jpg)

### Sometimes the image appears with inverted colours:

![Image from iOS (1)](https://user-images.githubusercontent.com/1874352/98843001-3fb1f200-2442-11eb-8c7c-bb504b196f21.jpg)

When taking this processor out of the request this bug goes away.

For the meantime we have had to turn off image resizing, which isn't ideal given our app does not control the source of images and large images will have an impact on memory etc.

--> Edit: We have since switch to using image resizing functions provided in UIKit as a custom processing step 

Any assistance would be much appreciated!

Many Thanks,

James @ nate

**Comment by kean** [comment] 2020-11-22 01:46
Hey, could you please provide the steps to reproduce it?

**Comment by james-ff** [comment] 2020-11-23 14:01
Example Image:
http://cdn.shopify.com/s/files/1/0468/2452/1890/products/SolaraSuncare-JuiceBoostSerum_1500x.jpg?v=1598293753

Example UIImageView sizes:
405x405, 125x125, 50x50

Example code:
```
let url = URL(string: "image_link")!
let options = ImageLoadingOptions(transition: .fadeIn(duration: 0.33))
let request = ImageRequest(url: url, processors: [ImageProcessors.Resize(size: self.imageView.bounds.size)])
Nuke.loadImage(with: request, options: options, into: self.imageView)
```

**Comment by kean** [comment] 2020-11-23 19:53
Hi, I tried this in iOS 11.3 and iOS 14.0 simulators and I can't reproduce it. Are there are additional options that need to be enabled, e.g. maybe some accessibility options?

**Comment by kean** [comment] 2020-11-26 15:59
I'm still not able to reproduce it. May I ask what `UIKit` resizing functions are you referring to? Is it `UIGraphicsImageRenderer`? I would appreciate if you could provide a sample.

**Comment by Fabezi** [comment] 2020-11-26 19:02
We are also experiencing this problem. This seems to have started after iOS 14.1, and for us, it happens somewhat randomly and only for some of our users. Even if they are using the same device and setup as I am, I was unable to reproduce this myself but after switching to a different resize method as suggested here, this did fix the problem. I can only guess this is some very weird iOS issue.

**Comment by james-ff** [comment] 2020-11-30 19:41
we now use the following UIKit implementation of resize image, instead of the nuke processor:

```swift

import UIKit

import func AVFoundation.AVMakeRect

import Nuke

let bounds = self.imageView.bounds
return ImageProcessors.Anonymous(id: "image-resize") { (image) -> PlatformImage? in
    let size = AVMakeRect(aspectRatio: image.size, insideRect: bounds).size
        return UIGraphicsImageRenderer(size: size).image { context in
            image.draw(in: CGRect(origin: .zero, size: size))
        }
    }
}
```

**Comment by kean** [comment] 2020-11-30 20:06
Thanks, @james-ff. `UIGraphicsImageRenderer` is a great API. Unfortunately, I was not able to find a similar API for macOS. I'm also not sure it's fully safe to use from background threads. So I would prefer to stick with `CGContext`. After all, `UIGraphicsImageRenderer` is just a wrapper for `CGContext` APIs.

Thanks for the link, but I would take it with a grain of salt. I reviewed this article last week and found some issues in it. For example, for `CGContext` approach they pass incorrect number of bytes per row – it's based on the size of the original image and not the size of the target (resized) image. It might result in unnecessarily large allocations.

I also recently re-ran the performance tests from this article. On iPhone 11 Pro running iOS 14.2 the results don't match. The fastest approach is #2 – based on `CGContext` – what Nuke uses today. That matches my expectations. `UIGraphicsImageRendererContext` is simply a wrapper on top of `CGContext.` I wouldn't expect it to be faster.

I slightly [changed the resizing](https://github.com/kean/Nuke/pull/408) in the latest release, Nuke 9.2. It no longer draws the images using the default color space and 32 bits per row. It now takes into account the format of the original image. As a result, it now supports extended color spaces, and can also save memory in situations where 32 bits are not necessary (e.g. grayscale jpeg). I hope that it also fixes the issue with colors. Even though I was not able to reproduce it, my assumption is that it has to do with the default color space and the conversion to this color space.

**Comment by kean** [comment] 2021-02-18 04:57
I'm going to close this, it appears that there were no new reports since [9.2.0](https://github.com/kean/Nuke/releases/tag/9.2.0) with a fix was released. Please feel free to re-open if you are still able to reproduce in 9.2.0 or more recent versions.

**Closed by kean** 2021-02-18 04:57 UTC
Labels: bug
